name: not_a_note
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  package_info_plus: ^3.0.2
  synchronized: ^3.0.0+3
  shared_preferences: ^2.0.15
  loading_indicator: ^3.1.0
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  intl: ^0.18.0
  geolocator: ^9.0.2
  device_info_plus: ^8.0.0
  local_auth: ^2.1.2
  flutter_secure_storage: ^7.0.1
  photo_view: ^0.14.0
  image_picker: ^0.8.7
  syncfusion_flutter_gauges: ^21.1.37
  snapping_sheet: ^3.1.0
  firebase_crashlytics: ^3.1.1
  firebase_core: ^2.10.0
  http_parser: ^4.0.2
  firebase_messaging: ^14.6.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/font/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/averta_regular_italic.otf
        - asset: assets/font/averta.otf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/images/logo.png"

# https://docs.flutter.dev/accessibility-and-localization/internationalization
# flutter pub global run intl_utils:generate
flutter_intl:
  enabled: true
  class_name: AppLanguage
  main_locale: vi
  arb_dir: lib/component/language
  output_dir: lib/component/language/generated